---
thresholds:
  status:
    - {color: "red", level: 0}
    - {color: "green", level: 1}
  interface_status:
    - {color: "blue", level: 0}
    - {color: "red", level: 1}
    - {color: "red", level: 10}
    - {color: "green", level: 11}
